### ISSUE TITLE
Error: Too few arguments to function Laravel\Nova\Resource::__construct(), 0 passed

### ISSUE THREAD

**Issue by lfleigl** [michielkempen/nova-polymorphic-field#1]
Hi.

I try your package, but get an Error:
`Too few arguments to function Laravel\Nova\Resource::__construct(), 0 passed in /Users/lars/Entwicklung/_research/Laravel/polymorph/vendor/michielkempen/nova-polymorphic-field/src/PolymorphicField.php on line 87 and exactly 1 expected`

I create a new Laravel Project, with the three models - but only ::make in the Nova\NewsPost->fields()
The PolymorphicField and HasPolymorphicFields are also use by this Nova-Ressource. Have I use it for the both models Article and Video also? And have I add the fields to this models, also?

![image](https://user-images.githubusercontent.com/1787705/45689841-40e27f80-bb55-11e8-9784-4aca8febe55f.png)

**Comment by michielkempen** [comment]
The second parameter in the `->type($name, $modelClass, $fields)` method should by the class of the polymorphic model, not the class of the resource.

So in your example use: `->type('Article', \App\Article::class, [...])`

**Comment by jasonlav** [comment]
Ran across same issue; solution resolved the issue.
